### ISSUE TITLE
Implement workflow for reporting Yoda issues and requests to Utrecht

### ISSUE THREAD

**Issue by peer35** [vu-rdm-tech/yoda-pilot#10]
Utrecht will look into providing access for our project team to their Jira instance (seems they can work with SurfConext)

**Comment by peer35** [comment]
We do have a slack channel now, but so far no involvement of Utrecht.

**Comment by peer35** [comment]
Apparently we can now use https://github.com/UtrechtUniversity/yoda/issues to report issues.

Need to ask for more info/guidance

**Comment by bgoli** [comment]
One way would be to open our issues here and then link to them from ones we raise at Utrecht. Random link to one of my other ones to test how this works: https://github.com/SystemsBioinformatics/cbmpy/issues/25

**Comment by peer35** [comment]
Looks to be fine as is. Agreed we should also create issue here and link to the one at uu.
