### ISSUE TITLE
Yoda 1.6 invitation screen: Terms of use are all UU

### ISSUE THREAD

**Issue by bgoli** [vu-rdm-tech/yoda-pilot#39]
![image](https://user-images.githubusercontent.com/5011985/104312754-57a40180-54d7-11eb-911a-ceb7223229dc.png)

**Comment by bgoli** [comment]
@peer35 is this just an artefact of the test environment? If so it can be closed.

**Comment by peer35** [comment]
Duplicate of https://github.com/vu-rdm-tech/yoda-pilot/issues/15
